export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const GET_ERRORS = 'GET_ERRORS';
export const LOAD_DEPARTMENTS = 'LOAD_DEPARTMENT';
export const SET_CLASS_TIMETABLE = 'SET_CLASS_TIMETABLE';
export const SET_PERSONAL_TIMETABLE = 'SET_PERSONAL_TIMETABLE';
export const SET_COURSES = 'SET_COURSES';
export const ADD_COURSE = 'ADD_COURSE';
